spring.application.name=PostApp

spring.datasource.url= jdbc:postgresql://localhost:5432/postapp
spring.datasource.username= postapp
spring.datasource.password= 123456

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

server.port=8080