-- liquibase formatted sql

-- changeset klikli:1
CREATE TABLE post_office(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(200) NOT NULL
);
CREATE TABLE postal_items(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(50) NOT NULL,
    index_recipient INTEGER NOT NULL,
    address_recipient VARCHAR(200) NOT NULL
);
-- changeset klikli:2
CREATE TABLE transactions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    post_office_id BIGINT REFERENCES post_office (id) NOT NULL,
    status VARCHAR(50) NOT NULL,
    postal_items_id BIGINT REFERENCES postal_items (id) NOT NULL
);
-- changeset klikli:3
ALTER TABLE transactions ADD CONSTRAINT postal_items_id_status_post_office_id UNIQUE (postal_items_id, status, post_office_id);




